[[history]]
== Коротка історія

Ця глава має стати коротким звітом про життя проекту Erlang.mk.

=== До Erlang.mk

Erlang.mk бере початок від проекту Cowboy. Cowboy починався як 
Rebar-проект і я, Loïc Hoguin, був задоволений ним впродовж декількох
років. Однак зчасом я почав дратуватися через деякі речі, зокрема
через погані початкові налаштування, іх зміну та загальні повільності.

Зокрема, на той момент коли я відмовився від Rebar, набор тестів 
для Cowboy займав приблизно 5 хвилин. Простий експеремент довів - 
простий виклик `ct_run` дає результат набагато швидше. 
4го січня 2013 року тести Cowboy були виконані швидше ніж за хвилину.

Після такого успіху я скоріше почав виключати з проекту залежність від 
Rebar та в знаменний день 5 січня 2013 року повністю звільнився від 
нього. Rebar та його концепція залежностей наклали значний відбиток
на розвиток Erlang.mk.

Erlang.mk було задумано.

Минуло кілька місяців і 1 травня 2013 року було створено репозиторій 
Erlang.mk. Erlang.mk побачив світ.

Я навіть не здогадувався наскільки він зростатиме.

=== Час життя проекту

Erlang.mk зчасом ставав все більш крупним файлом та почав працювати
з різними проектами, а не тільки з Cowboy. З моменту створення 
найбільший вклад у розвиток проекту внесли користувачі, тому що Erlang.mk 
звертався до багатьох людей з різними потребами, з якими ще не міг 
впоратися сам.

Проект було розбито на окремі файли, кожен з яких вирішував певну задачу.
Для складання єдиного файлу було написано сценарій збирання.

Тести були отримані від користувача, та згодом стали основою поточного, 
більш повного набору тестів. Виявилось що тестувати Makefile доволі 
просто.

Для рішення проблеми пошуку Erlang-проектів було додано індекс пакунків.

Після спроби визначити можливість співпраці інструментів збирання Erlang, 
було прийняте рішення покращення сумісності з існуючими проектами Rebar, 
змінивши Rebar та використовуючи його. Ця функія, що називається
autopatch, виявилась дуже успішною, та зробила Erlang.mk сумісним з 
більш ніж 90% існуючих Erlang-проектів.

Документація Erlang.mk була значно покращена, а влітку 2015 року 
з'явився сайт проекту.

Впродовж 2015 року Erlang.mk перейшов від простого зацікавлення до 
серйозної альтернативи іншим інструментам збирання Erlang. Значно 
збільшиласть кількість користувачів, Erlang.mk почали використовувати 
великі проекти, в тому числі RabbitMQ починаючи з версії 3.6.0.

Попереду світле майбутнє.
